apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cyclegan-trainer
  name: scb-b12-sl1-40h
spec:
  template:
    metadata:
      name: cyclegan-trainer
    spec:
      volumes:
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      - name: azurefile
        azureFile:
            secretName: azure-secret
            shareName: data
            readOnly: false      
      containers:
      - name: cyclegan-trainer
        command: ["/bin/sh", "-c"]
        args: ["export LD_LIBRARY_PATH='/usr/lib/x86_64-linux-gnu_custom:$LD_LIBRARY_PATH';  python cyclegan.py --checkpoint-freq 50 -s 50 -sd /data/samples/scb-b12-sl1-40h -i scb -t 1800 -b 12 -sl -lf 5 -cd /data/checkpoints/scb-b12-sl1-40h -log /data/logs/scb-b12-sl1-40h"]
        image: wbuchwalter/cyclegan
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/lib/x86_64-linux-gnu_custom
          name: libraries
        - mountPath: "/data"
          name: azurefile       
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cyclegan-trainer
  name: scb-b12-40h
spec:
  template:
    metadata:
      name: cyclegan-trainer
    spec:
      volumes:
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      - name: azurefile
        azureFile:
            secretName: azure-secret
            shareName: data
            readOnly: false      
      containers:
      - name: cyclegan-trainer
        command: ["/bin/sh", "-c"]
        args: ["export LD_LIBRARY_PATH='/usr/lib/x86_64-linux-gnu_custom:$LD_LIBRARY_PATH';  python cyclegan.py --checkpoint-freq 50 -s 50 -sd /data/samples/scb-b12-40h -i scb -t 2400 -b 12 -lf 5 -cd /data/checkpoints/scb-b12-40h -log /data/logs/scb-b12-40h"]
        image: wbuchwalter/cyclegan
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/lib/x86_64-linux-gnu_custom
          name: libraries
        - mountPath: "/data"
          name: azurefile       
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cyclegan-trainer
  name: san2sea-b12-40h
spec:
  template:
    metadata:
      name: cyclegan-trainer
    spec:
      volumes:
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      - name: azurefile
        azureFile:
            secretName: azure-secret
            shareName: data
            readOnly: false      
      containers:
      - name: cyclegan-trainer
        command: ["/bin/sh", "-c"]
        args: ["export LD_LIBRARY_PATH='/usr/lib/x86_64-linux-gnu_custom:$LD_LIBRARY_PATH';  python cyclegan.py --checkpoint-freq 50 -s 50 -sd /data/samples/san2sea-b12-40h -i san2sea -t 1800 -b 12 -lf 5 -cd /data/checkpoints/san2sea-b12-40h -log /data/logs/san2sea-b12-40h"]
        image: wbuchwalter/cyclegan
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/lib/x86_64-linux-gnu_custom
          name: libraries
        - mountPath: "/data"
          name: azurefile       
      restartPolicy: Never